from __future__ import annotations

from uni_kb.store.code_graph import CodeGraph


def generate_migration_checklist(graph: CodeGraph, title: str = "Migration Plan") -> str:
    lines: list[str] = [
        f"# {title}",
        "",
        "## Overview",
        f"- **Total nodes:** {graph.node_count()}",
        f"- **Total edges:** {graph.edge_count()}",
        "",
        "## Migration Order",
        "",
    ]
    try:
        order = graph.topological_sort()
    except Exception:
        order = list(graph.graph.nodes())

    for i, node_id in enumerate(order, 1):
        node_data = graph.graph.nodes.get(node_id, {})
        node_type = node_data.get("type", "Unknown")
        name = node_data.get("name", node_id)
        lines.append(f"{i}. **[`{node_type}`]** {name}")

        deps = graph.get_dependencies(node_id)
        if deps:
            dep_names: list[str] = []
            for did in deps:
                ddata = graph.graph.nodes.get(did, {})
                dep_names.append(ddata.get("name", did))
            lines.append(f"   - Depends on: {', '.join(dep_names)}")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated by uni-kb migration_checklist generator — {len(order)} items_")
    return "\n".join(lines)
